name: "Run unit tests"

on:
  push:

jobs:
  release:
    name: Generate new release
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\/v/}

      - name: Create .env file
        run: |
          touch .env
          echo INFURA_API_KEY=${{ secrets.INFURA_API_KEY }} >> .env
          echo MNEMONIC=${{ secrets.MNEMONIC }} >> .env

      - name: Yarn Install
        run: yarn install

      - name: Yarn Compile
        run: yarn compile

      - name: Yarn Typechain
        run: yarn typechain

      - name: Run tests
        id: run_tests
        run: yarn test
