name: "Run unit tests"

on:
  push:

jobs:
  release:
    name: Generate new release
    runs-on: ubuntu-latest
    env:
      working-directory: .

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\/v/}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Node Version
        run: node --version

      - name: Npm Install
        run: npm i --save
        working-directory: ${{ env.working-directory }}

      - name: Run tests
        id: run_tests
        run: npm run test
