name: "Run unit tests"

on:
  push:

jobs:
  release:
    name: Generate new release
    runs-on: ubuntu-latest
    env:
      working-directory: .

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Npm Install
        run: npm i --save
        working-directory: ${{ env.working-directory }}

      - name: Run tests
        id: run_tests
        run: npm run test
